name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js with pnpm cache
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install dependencies using pnpm
      run: pnpm install

    - name: Build Nuxt.js project
      run: pnpm run build
