name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js with npm
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies using npm
        run: npm install

      - name: Build Nuxt.js project
        run: npm run build

      - name: Move build to destination directory
        run: |
          mkdir -p /home/ubuntu/ghdeploy
          mv -f .output/server /home/ubuntu/ghdeploy/
          mv -f .output/public /home/ubuntu/ghdeploy/
          mv -f .output/nitro.json /home/ubuntu/ghdeploy/
