name: Deploy Nuxt.js Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Cache pnpm cache
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Install dependencies using pnpm
      run: pnpm install

    - name: Build Nuxt.js project
      run: npm run build # or yarn build if you are using yarn

    - name: Move build to destination directory
      run: |
        mkdir -p /home/ubuntu/ghdeploy
        mv -f .output/server /home/ubuntu/ghdeploy/
        mv -f .output/public /home/ubuntu/ghdeploy/
        mv -f .output/nitro.json /home/ubuntu/ghdeploy/

    - name: Restart systemd service
      run: |
        systemctl restart nuxt-chat.service

    - name: Notify GitHub Actions that the deploy is complete
      run: |
        echo "Deployment is complete!" # Custom message to show that deployment is done
