name: Deploy Nuxt.js Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build Nuxt.js project
      run: npm run build

    - name: Serve Nuxt.js project in the background
      run: |
        nohup node .output/server/index.mjs &
        echo $! > server.pid  # Save the server process ID

    - name: Notify GitHub Actions that the deploy is complete
      run: |
        echo "Deployment is complete!"  # Custom message to show that deployment is done
